[settings]
lockfile = true

[tools]
'github:WebAssembly/binaryen' = 'version_126'
'github:wasm-bindgen/wasm-bindgen' = '0.2.114'
bun = '1.3.10'

[tasks.'build:wasm']
run = '''
cargo build -p chocolate-wasm \
	--target=wasm32-unknown-unknown --profile=release-minified &&
wasm-bindgen \
	--target=deno --out-dir=build/wasm --out-name=chocolate \
	--remove-name-section --remove-producers-section \
	--omit-default-module-path --encode-into=always \
	target/wasm32-unknown-unknown/release-minified/chocolate_wasm.wasm &&
sed -i \
	"s|new URL('chocolate_bg.wasm', import.meta.url)|'./chocolate_bg.wasm'|" \
	build/wasm/chocolate.js &&
wasm-opt \
	--quiet --fast-math --enable-bulk-memory --all-features -O \
	build/wasm/chocolate_bg.wasm -o build/wasm/chocolate_bg.wasm
'''

[tasks.'build:web']
depends = ['build:wasm']
run = '''
bun build ./src/web/index.html --outdir=./dist \
	--target=browser --format=esm --minify &&
cp ./build/wasm/chocolate_bg.wasm dist/chocolate_bg.wasm
'''

[tasks.'watch:web']
depends = ['build:wasm']
run = 'bun run ./serve.ts'

[tasks.'build:exe']
run = 'cargo build -p chocolate --release'
